// Theme.ts
import { defineConfig, defineRecipe } from "@chakra-ui/react";

// 👇 반드시 export
export const buttonRecipe = defineRecipe({
  base: {
    fontFamily: "Inter",
    fontWeight: "400",
    color: "#000",
    lineHeight: "1",
    borderRadius: "5px",
  },
  variants: {
    variant: {
      solid: {
        minW: "auto",
        h: "34px",
        color: "#fff",
        px: "15px",
        bg: "#2D2D2D",
        _hover: { bg: "#444" },
      },
      ghost: {
        justifyContent: "flex-start",
        minW: "auto",
        h: "auto",
        fontSize: "14px",
        color: "#000",
        fontWeight: "700",
        p: "0",
        _hover: { bg: "transparent" },
      },

      typeIcon: {
        pos: "relative",
        w: "24px",
        minW: "auto",
        h: "24px",
        fontSize: "24px",
        border: "none",
        borderRadius: "0",
        p: "0",
        m: "0",
        bg: "transparent",
      },
      typeIconLg: {
        pos: "relative",
        w: "64px",
        minW: "auto",
        h: "64px",
        fontSize: "24px",
        border: "none",
        borderRadius: "0",
        p: "0",
        m: "4px",
        bg: "#D9D9D9",
        _hover: { bg: "#eee" },
      },
      typeIconSm: {
        pos: "relative",
        w: "12px",
        minW: "auto",
        h: "12px",
        fontSize: "12px",
        border: "none",
        borderRadius: "0",
        p: "0",
        m: "0",
        bg: "transparent",
      },
      typeGrayLg: {
        h: "35px",
        fontSize: "19px",
        px: "10px",
        bg: "#f44",
        _hover: { bg: "#ff5" },
      },
      typeTableBtn: {
        h: "30px",
        fontSize: "14px",
        color: "#000",
        fontWeight: "400",
        borderRadius: "5px",
        border: "solid 1px #e5e5e5",
        px: "12px",
        m: "0 5px",
        bg: "#fff",
        _hover: { bg: "#eee" },
      },
      typeModalBtn: {
        h: "34px",
        fontSize: "14px",
        fontWeight: "400",
        color: "#fff",
        px: "20px",
        bg: "#2D2D2D",
        _hover: { bg: "#444" },
      },
      typePopoverBtn: {
        w: "120px",
        h: "34px",
        fontSize: "14px",
        fontWeight: "500",
        color: "#fff",
        px: "20px",
        ml: "10px",
        bg: "#2D2D2D",
        _hover: { bg: "#444" },
      },
      typePopoverWhiteBtn: {
        w: "120px",
        h: "34px",
        fontSize: "14px",
        fontWeight: "400",
        color: "blackAlpha.800",
        border: "solid 1px #e5e5e5",
        px: "20px",
        ml: "10px",
        bg: "#fff",
        _hover: { bg: "#eee" },
      },
      typeWhiteBtnSm: {
        h: "32px",
        fontSize: "14px",
        fontWeight: "400",
        color: "blackAlpha.800",
        border: "solid 1px #e5e5e5",
        px: "10px",
        ml: "10px",
        bg: "#fff",
        _hover: { bg: "#eee" },
      },
      typeBlackBtnSm: {
        h: "32px",
        fontSize: "14px",
        fontWeight: "400",
        color: "#fff",
        border: "solid 1px #2D2D2D",
        px: "10px",
        ml: "10px",
        bg: "#2D2D2D",
        _hover: { bg: "#444" },
      },
      typeDrawerClose: {
        pos: "relative",
        w: "24px",
        minW: "auto",
        h: "18px",
        fontSize: "24px",
        color: "#999",
        border: "none",
        borderLeft: "solid 2px #999",
        borderRadius: "0",
        p: "0",
        m: "0",
        bg: "transparent",
        outline: "none",
        _focusVisible: { boxShadow: "none" },
      },
      typeCopyBtn: {
        h: "14px",
        fontSize: "12px",
        fontWeight: "600",
        color: "#000",
        p: "0",
        bg: "transparent",
        _hover: { color: "#0ACF83" },
      },
      typeAlertWhiteBtn: {
        w: "calc(100%/2 - 5px)",
        h: "32px",
        fontSize: "14px",
        fontWeight: "400",
        color: "blackAlpha.800",
        border: "solid 1px #e5e5e5",
        px: "20px",
        bg: "#fff",
        _hover: { bg: "#eee" },
      },
      typeAlertBlackBtn: {
        w: "calc(100%/2 - 5px)",
        h: "32px",
        fontSize: "14px",
        fontWeight: "700",
        color: "#fff",
        border: "solid 1px #2d2d2d",
        px: "20px",
        bg: "#2d2d2d",
        _hover: { bg: "#444" },
      },
      paginationBtn: {
        fontSize: "24px",
        color: "blackAlpha.300",
        px: "7px",
        _hover: { color: "blackAlpha.900" },
      },
      typePopoverMoreBtn: {
        w: "48px",
        h: "32px",
        fontSize: "24px",
        color: "blackAlpha.900",
        p: "0",
        ml: "10px",
        border: "solid 1px #e5e5e5",
        _hover: { color: "#fff", bg: "#0acf83" },
      },
      typeSelectBtn: {
        border: "solid 1px #e5e5e5",
        px: "10px",
        ps: "15px",
        bg: "#fff",
        "& svg": {
          transition: "transform 0.2s ease-out",
          transformOrigin: "center center",
        },
        '&[aria-expanded="true"] svg': {
          transform: "rotate(-180deg)",
        },
      },
      typeSelectModalBtn: {
        w: "100%",
        h: "32px",
        fontSize: "14px",
        fontWeight: "400",
        textAlign: "left",
        border: "solid 1px #e5e5e5",
        px: "10px",
        ps: "15px",
        bg: "#fff",
        "& svg": {
          transition: "transform 0.2s ease-out",
          transformOrigin: "center center",
        },
        '&[aria-expanded="true"] svg': {
          transform: "rotate(-180deg)",
        },
      },
      typeSelectPopoverBtn: {
        w: "100%",
        h: "32px",
        fontSize: "14px",
        fontWeight: "400",
        textAlign: "left",
        border: "solid 1px #e5e5e5",
        px: "10px",
        ps: "15px",
        bg: "#fff",
        "& svg": {
          transition: "transform 0.2s ease-out",
          transformOrigin: "center center",
        },
        '&[aria-expanded="true"] svg': {
          transform: "rotate(-180deg)",
        },
      },
      typeAvatar: {
        h: "30px",
        p: "0",
        m: "0",
        "& svg": {
          transition: "transform 0.2s ease-out",
          transformOrigin: "center center",
        },
        '&[aria-expanded="true"] svg': {
          transform: "rotate(-180deg)",
        },
      },
    },
  },
});

// config는 그대로
const config = defineConfig({
  theme: {
    recipes: {
      button: buttonRecipe,
    },
  },
});

export default config;
